schema_version: 1
experiment_name: audit-yardrat-subset
description: Historic reproducibility batch with 22 run entries
run_entries:
- boolq:model=lmsys/vicuna-7b-v1.3,data_augmentation=canonical
- entity_data_imputation:dataset=Buy,model=lmsys/vicuna-7b-v1.3
- entity_data_imputation:dataset=Restaurant,model=lmsys/vicuna-7b-v1.3
- entity_matching:dataset=Abt_Buy,model=lmsys/vicuna-7b-v1.3
- entity_matching:dataset=Beer,model=lmsys/vicuna-7b-v1.3
- entity_matching:dataset=Dirty_iTunes_Amazon,model=lmsys/vicuna-7b-v1.3
- gsm:model=lmsys/vicuna-7b-v1.3
- imdb:model=lmsys/vicuna-7b-v1.3,data_augmentation=canonical
- lsat_qa:task=all,method=multiple_choice_joint,model=lmsys/vicuna-7b-v1.3
- mmlu:subject=abstract_algebra,method=multiple_choice_joint,model=lmsys/vicuna-7b-v1.3,data_augmentation=canonical
- mmlu:subject=college_chemistry,method=multiple_choice_joint,model=lmsys/vicuna-7b-v1.3,data_augmentation=canonical
- mmlu:subject=computer_security,method=multiple_choice_joint,model=lmsys/vicuna-7b-v1.3,data_augmentation=canonical
- mmlu:subject=econometrics,method=multiple_choice_joint,model=lmsys/vicuna-7b-v1.3,data_augmentation=canonical
- mmlu:subject=us_foreign_policy,method=multiple_choice_joint,model=lmsys/vicuna-7b-v1.3,data_augmentation=canonical
- narrative_qa:model=lmsys/vicuna-7b-v1.3,data_augmentation=canonical
- quac:model=lmsys/vicuna-7b-v1.3,data_augmentation=canonical
- synthetic_reasoning:mode=induction,model=lmsys/vicuna-7b-v1.3
- synthetic_reasoning:mode=pattern_match,model=lmsys/vicuna-7b-v1.3
- synthetic_reasoning:mode=variable_substitution,model=lmsys/vicuna-7b-v1.3
- synthetic_reasoning_natural:difficulty=easy,model=lmsys/vicuna-7b-v1.3
- synthetic_reasoning_natural:difficulty=hard,model=lmsys/vicuna-7b-v1.3
- truthful_qa:task=mc_single,method=multiple_choice_joint,model=lmsys/vicuna-7b-v1.3,data_augmentation=canonical
max_eval_instances: 1000
suite: audit-yardrat-subset
mode: compute_if_missing
materialize: symlink
backend: tmux
devices: '0'
tmux_workers: 1
local_path: prod_env
precomputed_root:
require_per_instance_stats: true
model_deployments_fpath: configs/debug/vicuna_no_chat_template.yaml
enable_huggingface_models: []
enable_local_huggingface_models: []
